dep 'apps' do
  requires 'Adium.app',
           '1Password.app',
           'Dropbox.app',
           'Firefox.app',
           'benhoskings:Fluid.app',
           'GitX.app',
           'Google Chrome.app',
           'Growl.prefpane',
           'benhoskings:LaunchBar.app',
           'MacVim.app',
           'Mailplane.app',
           'MockSmtp.app',
           'RubyMine.app',
           'Sequel Pro.app',
           'Skitch.app',
           'Skype.app',
           'TextMate.app',
           'Things.app',
           'textmate'
end